title: Portál otevřených dat Ministerstva financí
title_short: Otevřená data MFČR
description: Otevřená data Ministerstva financí
email: martin.kopecek@mfcr.cz

site_url: "https://opendata.mfcr.cz"
exports_url: "https://opendata.mfcr.cz/exports"
catalog_url: "https://opendata.mfcr.cz/catalog"

collections_dir: collections

collections:
  organizations:
    output: true
  apps:
    output: false
  posts:
    output: false
  stories:
    output: true
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

  - scope:
      path: ""
      type: "topics"
    values:
      layout: topic

  - scope:
      path: ""
      type: "organizations"
    values:
      layout: "organization"
