# SITE METADATA
title: Portál otevřených dat Ministerstva financí
title_short: Otevřená data MFČR
description: Otevřená data Ministerstva financí
email: martin.kopecek@mfcr.cz

site_url: "https://opendata.mfcr.cz"
exports_url: "https://opendata.mfcr.cz/exports"
catalog_url: "/catalog"

# BUILD SETTINGS
url: https://opendata.mfcr.cz
exclude:
  - docker-compose.yml
  - docker-compose.prod.yml
  - Dockerfile
  - nginx.conf

kramdown:
  header_offset: 1
  smart_quotes: sbquo,rsquo,bdquo,rdquo
  auto_id_prefix: toc-

plugins:
  - jekyll-toc
  - jekyll-redirect-from

toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6

collections_dir: collections

collections:
  organizations:
    output: true
  apps:
    output: false
  posts:
    output: false
  stories:
    output: true
  topics:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

  - scope:
      path: ""
      type: "topics"
    values:
      layout: topic

  - scope:
      path: ""
      type: "organizations"
    values:
      layout: "organization"


