title: Otevřená data Ministerstva financí
title_short: Otevřená data MFČR
description: Otevřená data Ministerstva financí
email: martin.kopecek@mfcr.cz

exports_url: "https://opendata.mfcr.cz/exports"
catalog_url: "https://opendata.mfcr.cz/catalog"

collections_dir: collections

collections:
  categories:
    output: true
  organizations:
    output: true
  posts:
    output: false
  stories:
    output: true
  systems:
    output: true
  topics:
    output: true


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

  - scope:
      path: ""
      type: "topics"
    values:
      layout: topic
      
  - scope:
      path: ""
      type: "systems"
    values:
      layout: "system"

  - scope:
      path: ""
      type: "organizations"
    values:
      layout: "organization"

  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"