version: '2'

services:
  web:
    image: jekyll/jekyll
    command: jekyll serve --force_polling --config _config.yml,_config_dev.yml
    environment:
      JEKYLL_ENV: docker
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - jekyll_cache:/usr/local/bundle

volumes:
  jekyll_cache: