title: Portál otevřených dat Ministerstva financí
title_short: Otevřená data MFČR
description: Otevřená data Ministerstva financí
email: martin.kopecek@mfcr.cz

site_url: "https://data.mf.gov.cz"
exports_url: "https://data.mf.gov.cz/exports"
catalog_url: "/catalog"
status_url: https://stats.uptimerobot.com/pB6Bntz7LY