# endpoint: http://localhost:3030/lkod/sparql
endpoint: https://opendata.mfcr.cz/lod/sparql
# publishers:
#   - https://data.gov.cz/zdroj/ovm/MinFin

# ordering: "generic"
ordering: "arq_collation" # use function http://jena.apache.org/ARQ/function#collation for ordering taking into account locale. works only with Jena Fuseki SPARQL endpoint
