backend:
  name: github
  repo: otevrena-data-mfcr/opendata-web
  branch: master # Branch to update
  base_url: https://opendata.mfcr.cz # Path to ext auth provider

media_folder: assets/content

locale: cs

collections:
  - name: stories
    label: Návody
    label_singular: Návody
    folder: collections/_stories/
    create: true
    editor:
      preview: false
    fields:
      - { label: Titulek, name: title, widget: string }
      - { label: Krátké shrnutí, name: description, widget: string }
      - { label: Typ, name: type, widget: select, options: ["jupyter", "html"] }
      - { label: GitHub, name: github, widget: string }
      - { label: Obsah stránky, name: body, widget: markdown }

  - name: topics
    label: Témata
    label_singular: Téma
    folder: collections/_topics/
    create: true
    editor:
      preview: true
    fields:
      - { label: Titulek, name: title, widget: string }
      - { label: Zkrácený titulek, name: short_title, widget: string }
      - { label: Krátké shrnutí, name: description, widget: string }
      - { label: Datové sady, name: datasets, widget: list }
      - label: Jiné zdroje
        name: links
        widget: list
        fields: 
          - {label: Název, name: title, widget: string }
          - {label: Krátké shrnutí, name: description, widget: string }
          - {label: URL, name: url, widget: string }
