backend:
  name: github
  repo: otevrena-data-mfcr/opendata-web
  branch: master # Branch to update
  base_url: https://opendata.mfcr.cz # Path to ext auth provider

publish_mode: editorial_workflow

media_folder: assets/content/uploads

locale: cs

collections:
  - name: topics
    label: Témata
    label_singular: Téma
    folder: collections/_topics/
    create: true
    editor:
      preview: false
    fields:
      - { label: Titulek, name: title, widget: string }
      - { label: Zkrácený titulek, name: short_title, widget: string, required: false}
      - { label: Krátké shrnutí, name: description, widget: string, required: false }
      - label: Datové sady
        label_singular: Datová sada
        name: datasets
        widget: list
        summary: '{{fields.iri}}'
        field: { label: IRI datové sady, name: iri, widget: string }
        required: false
      - label: Jiné zdroje
        name: links
        widget: list
        fields: 
          - {label: Název, name: title, widget: string }
          - {label: Krátké shrnutí, name: description, widget: string }
          - {label: URL, name: url, widget: string }
        required: false
      - { label: Obsah stránky, name: body, widget: markdown }

  - name: stories
    label: Návody
    label_singular: Návod
    folder: collections/_stories/
    create: true
    editor:
      preview: false
    fields:
      - { label: Titulek, name: title, widget: string }
      - { label: Krátké shrnutí, name: description, widget: string, required: false }
      - { label: Typ, name: type, widget: select, options: ["jupyter", "html"] }
      - { label: GitHub, name: github, widget: string, required: false }
      - { label: Obsah stránky, name: body, widget: markdown }
  
  - name: apps
    label: Aplikace
    folder: collections/_apps
    create: true
    editor:
      preview: false
    fields:
      - { label: Titulek, name: title, widget: string }
      - { label: Obrázek, name: description, widget: image, required: false }
      - { label: Odkaz, name: link, widget: string }
      - { label: Obsah stránky, name: body, widget: markdown }