name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to registry
        uses: docker/build-push-action@v5
        with:
          build-args: NG_CONFIGURATION=production
          push: true
          context: .
          tags: "ghcr.io/${{ github.repository_owner }}/opendata-portal:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
